spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/spacron_db
spring.datasource.username=postgres
spring.datasource.password=Spacron123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Force clean connection on restart
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.main.banner-mode=off
